# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-19 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo', '0002_auto_20161204_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='installedbuilddepends',
            unique_together=set([]),
        ),
    ]
