# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo', '0004_remove_buildinfo_raw_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedbuilddepends',
            name='binary',
        ),
        migrations.RemoveField(
            model_name='installedbuilddepends',
            name='buildinfo',
        ),
        migrations.DeleteModel(
            name='InstalledBuildDepends',
        ),
    ]
