# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(8, b'3479abcdefghijkmnopqrstuvwxyz'), **{}), max_length=8, unique=True)),
                ('uid', models.CharField(max_length=512)),
                ('node', models.CharField(max_length=512)),
                ('raw_text', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('buildinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='buildinfo.Buildinfo')),
            ],
            options={
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
    ]
