# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
        ('buildinfo_submissions', '0002_remove_submissions_without_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='keys.Key'),
        ),
    ]
