# Generated by Django 1.10.2 on 2016-11-03 20:30
from __future__ import unicode_literals

from django.db import migrations

def forwards(apps, schema_editor):
    if not schema_editor.connection.alias == 'default':
        return

    Key = apps.get_model('keys', 'Key')
    Submission = apps.get_model('buildinfo_submissions', 'Submission')

    for x in Submission.objects.all():
        x.key = Key.objects.get_or_create(uid=x.uid)[0]
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo_submissions', '0003_submission_key'),
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
