# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-04 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo_submissions', '0005_auto_20161103_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='node',
        ),
    ]
