# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-07 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo_submissions', '0006_remove_submission_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='raw_text',
        ),
    ]
